name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - run: cargo test

      - name: Install wasm-pack
        run: cargo install --git https://github.com/rustwasm/wasm-pack

      - run: pnpm install
      - name: Install playwright browsers
        run: pnpm dlx playwright install --with-deps

      - run: pnpm run build:release

      - run: pnpm run test
